### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'head')

### ISSUE THREAD

**Issue by drazisil** [Ardiannn08/resolve-outdated-comment#7]
```
 TypeError: Cannot read properties of undefined (reading 'head')
    at getPullRequestNumber (/home/runner/work/_actions/Ardiannn08/resolve-outdated-comment/v1.3/dist/index.js:9824:58)
    at getReviewThreadList (/home/runner/work/_actions/Ardiannn08/resolve-outdated-comment/v1.3/dist/index.js:9808:32)
    at getAllReviewThreadList (/home/runner/work/_actions/Ardiannn08/resolve-outdated-comment/v1.3/dist/index.js:9760:38)
    at run (/home/runner/work/_actions/Ardiannn08/resolve-outdated-comment/v1.3/dist/index.js:9695:23)
    at /home/runner/work/_actions/Ardiannn08/resolve-outdated-comment/v1.3/dist/index.js:9855:1
    at /home/runner/work/_actions/Ardiannn08/resolve-outdated-comment/v1.3/dist/index.js:9857:3
    at Object.<anonymous> (/home/runner/work/_actions/Ardiannn08/resolve-outdated-comment/v1.3/dist/index.js:9860:12)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
```

Happy to help troubleshoot this if needed. yM brain is just too full/gone to directly troubleshoot it myself right now.

**Comment by joshAtRula** [comment]
We're experiencing this too -- @Ardiannn08 any thoughts here?

**Comment by joshAtRula** [comment]
Adding some debug logging to the job, I see that the context of my PR is missing the `pull_request` property to key in on, despite my whole workflow only triggering on PRs:
```  workflow_dispatch: {}
  pull_request:
    types: [opened, reopened, labeled, synchronize]
```

It looks like the goal of that property `github.context.payload.pull_request.head.ref` is to get the branch name for the source of the PR. It looks like that property is also available at `github.context.payload.ref` (e.g. value: `"ref": "refs/heads/my_branch",`), but even trying this property in my fork, I don't get the expected response in the result field: `
return result.repository.pullRequests.edges[0].node.number;`

Not sure the way you'd prefer to resolve this

**Comment by jeantristan** [comment]
same error here
